#!/usr/bin/env bash

if ! command -v jbang >/dev/null 2>&1; then
    echo "jbang is required"
    exit 1
fi

if ! command -v docker >/dev/null 2>&1; then
    echo "docker is required"
    exit 1
fi

if [ "$#" -eq 0 ]; then
    echo "At least one filter keyword (Java Main-Class name or JAR path substring) must be provided!" > /dev/stderr
    exit 1
fi

DIR="$(dirname "$(readlink -f "$0")")"

function cleanup() {
    docker compose --file "${DIR}/compose.yml" down --volumes >/dev/null 2>&1
    kill "${agent_pid}" >/dev/null 2>&1
}
trap cleanup EXIT

cleanup
docker compose --file "${DIR}/compose.yml" up --detach >/dev/null 2>&1

# TODO this should not use --fresh for release (non-SNAPSHOT) versions
jbang --quiet --fresh io.cryostat:cryostat-agent:0.7.0-SNAPSHOT:shaded \
    -Dio.cryostat.agent.shaded.org.slf4j.simpleLogger.defaultLogLevel=off \
    -Dcryostat.agent.api.writes-enabled=true \
    -Dcryostat.agent.baseuri=http://localhost:8282 \
    -Dcryostat.agent.webclient.tls.required=false \
    -Dcryostat.agent.callback.scheme=http \
    -Dcryostat.agent.callback.host-name=localhost \
    -Dcryostat.agent.harvester.template=Continuous \
    -Dcryostat.agent.harvester.period-ms=30000 \
    -Dcryostat.agent.harvester.max-size-b=20971520 \
    -Dcryostat.agent.harvester.max-files=5 \
    --watch --watch-include "$@" &

agent_pid=$!

while ! docker exec -it cryostat-local-db-1 sh -c 'pg_isready -p 5444 -U cryostat -d cryostat || exit 1' >/dev/null 2>&1 ; do
    sleep 2
done
sleep "${ADDITIONAL_DB_START_SECONDS:-2}"

AWS_ACCESS_KEY_ID=access_key \
    AWS_SECRET_ACCESS_KEY=secret_key \
    CRYOSTAT_AGENT_TLS_REQUIRED=false \
    CRYOSTAT_AUDIT_ENABLED=true \
    CRYOSTAT_DISCOVERY_JDP_ENABLED=true \
    QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://localhost:5444/cryostat \
    QUARKUS_DATASOURCE_PASSWORD=cryostat \
    QUARKUS_DATASOURCE_USERNAME=cryostat \
    QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=none \
    QUARKUS_HIBERNATE_ORM_SQL_LOAD_SCRIPT=no-file \
    QUARKUS_HTTP_HOST=localhost \
    QUARKUS_HTTP_PORT=8282 \
    QUARKUS_LOG_LEVEL=off \
    QUARKUS_HTTP_ACCESS_LOG_ENABLED=false \
    QUARKUS_S3_AWS_REGION=us-east-1 \
    QUARKUS_S3_ENDPOINT_OVERRIDE=http://localhost:8333 \
    QUARKUS_S3_PATH_STYLE_ACCESS=true \
    STORAGE_EXT_URL=/storage/ \
    STORAGE_METADATA_STORAGE_MODE=tagging \
    STORAGE_PRESIGNED_DOWNLOADS_ENABLED=false \
    STORAGE_PRESIGNED_TRANSFERS_ENABLED=false \
    jbang "${DIR}/bin/cryostat-4.2.0-SNAPSHOT-runner.jar" >/dev/null 2>&1
